apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfy-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfy-postgres-db
  template:
    metadata:
      labels:
        app: devfy-postgres-db
    spec:
      containers:
        - name: devfy-postgres-db
          image: natanista/natanista-hub:devfy-postgres-db
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: devfy-postgres-db
spec:
  selector:
    app: devfy-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

